[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz = { runs = 256 }
optimizer = true
optimizer_runs = 800

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[profile.ci]
no_match_test = "testSim"
fuzz = { runs = 5_000, max_test_rejects = 1000000 }

[profile.sim]
match_test = "testSim"
fuzz = { runs = 5_000, max_test_rejects = 1000000 }

[fmt]
int_types = "long"
line_length = 120
number_underscore = "thousands"
override_spacing = false
quote_style = "double"
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[doc]
book = "book.toml"