name: Build and Compare Forge Docs

on:
  push:
    branches: ["forge-docs"]

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build and compare forge docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge doc
        run: |
          forge doc --build
        id: doc

      - name: Compare docs
        run: |
          git diff --quiet || (echo "Docs were not built before commit" && exit 1)
